require("plugin_config.telescope")
require("plugin_config.lualine")
require("plugin_config.treesitter")
require("plugin_config.colorscheme")
require("plugin_config.autoclose")
require("plugin_config.indent-blankline")
require("plugin_config.gitsigns")
require("plugin_config.nvim-comment")
